name: Cf-build

on: 
  release:
    types: [created]

jobs:        
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64, mips, mipsle]
    steps:
    - uses: actions/checkout@v3
    - name: Cloning repo
      run: |
        rm -rf ./{,.[!.],..?}*
        git clone https://github.com/cloudflare/cloudflared ./tmp/
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/cloudflared"
        binary_name: "cloudflared"
        ldflags: "-w -s"
        executable_compression: "upx -v"
        overwrite: true
        release_name: "cloudflared"
        
